/* -LICENSE-START-
 ** Copyright (c) 2018 Blackmagic Design
 **  
 ** Permission is hereby granted, free of charge, to any person or organization 
 ** obtaining a copy of the software and accompanying documentation (the 
 ** "Software") to use, reproduce, display, distribute, sub-license, execute, 
 ** and transmit the Software, and to prepare derivative works of the Software, 
 ** and to permit third-parties to whom the Software is furnished to do so, in 
 ** accordance with:
 ** 
 ** (1) if the Software is obtained from Blackmagic Design, the End User License 
 ** Agreement for the Software Development Kit ("EULA") available at 
 ** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
 ** 
 ** (2) if the Software is obtained from any third party, such licensing terms 
 ** as notified by that third party,
 ** 
 ** and all subject to the following:
 ** 
 ** (3) the copyright notices in the Software and this entire statement, 
 ** including the above license grant, this restriction and the following 
 ** disclaimer, must be included in all copies of the Software, in whole or in 
 ** part, and all derivative works of the Software, unless such copies or 
 ** derivative works are solely in the form of machine-executable object code 
 ** generated by a source language processor.
 ** 
 ** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 ** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 ** DEALINGS IN THE SOFTWARE.
 ** 
 ** A copy of the Software is available free of charge at 
 ** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
 ** 
 ** -LICENSE-END-
 */

#include "DeckLinkCaptureDevice.h"
#include <CoreVideo/CVPixelBuffer.h>

static const BMDPixelFormat kDevicePixelFormat	= bmdFormat10BitYUV;

// DeckLinkCaptureDevice
DeckLinkCaptureDevice::DeckLinkCaptureDevice(com_ptr<IDeckLink>& deckLink) :
m_refCount(1),
m_deviceID(kInvalidDevice),
m_init(false),
m_statusListener(nullptr),
m_errorListener(nullptr),
m_deviceState(kDeviceIOIdle),
m_deckLink(deckLink),
m_deckLinkInput(nullptr),
m_displayMode(bmdModeNTSC),
m_pixelFormat(kDevicePixelFormat),
m_frameDuration(0),
m_timeScale(0),
m_videoFrameProperties(nullptr),
m_mediaWriter(nullptr),
m_videoInputConnections(bmdVideoConnectionUnspecified),
m_activeVideoInputConnection(bmdVideoConnectionUnspecified),
m_eotf(EOTF::SDR),
m_detectFormat(false),
m_supportsFormatDetection(false),
m_videoInputEnabled(false),
m_audioInputEnabled(false),
m_isAvailable(true),
m_lastValidFrameStatus(kCaptureSignalUnknown)
{
	com_ptr<IDeckLinkProfileAttributes>	attributes(IID_IDeckLinkProfileAttributes, m_deckLink);
	if (!m_deckLink || !attributes)
		return;

	attributes->GetString(BMDDeckLinkDisplayName, &m_displayName);
	attributes->GetFlag(BMDDeckLinkSupportsInputFormatDetection, &m_supportsFormatDetection);
	
	m_deviceID = GetDeckLinkID(deckLink);
	
	// Enable format detection by default if supported
	m_detectFormat = m_supportsFormatDetection;
	
	m_fileWriterQueue = dispatch_queue_create("CoreMedia file writer queue", nullptr);
}

DeckLinkCaptureDevice::~DeckLinkCaptureDevice()
{
}

HRESULT DeckLinkCaptureDevice::QueryInterface(REFIID iid, LPVOID *ppv)
{
	CFUUIDBytes	iunknown;
	HRESULT		result = E_NOINTERFACE;

	*ppv = NULL;

	iunknown = CFUUIDGetUUIDBytes(IUnknownUUID);
	if (memcmp(&iid, &iunknown, sizeof(REFIID)) == 0)
	{
		*ppv = this;
		AddRef();
		result = S_OK;
	}
	else if (memcmp(&iid, &IID_IDeckLinkInputCallback, sizeof(REFIID)) == 0)
	{
		*ppv = (IDeckLinkInputCallback*)this;
		AddRef();
		result = S_OK;
	}
	else if (memcmp(&iid, &IID_IDeckLinkNotificationCallback, sizeof(REFIID)) == 0)
	{
		*ppv = (IDeckLinkNotificationCallback*)this;
		AddRef();
		result = S_OK;
	}
	else if (memcmp(&iid, &IID_IDeckLinkProfileCallback, sizeof(REFIID)) == 0)
	{
		*ppv = (IDeckLinkProfileCallback*)this;
		AddRef();
		result = S_OK;
	}

	return result;
}

ULONG DeckLinkCaptureDevice::AddRef()
{
	return ++m_refCount;
}

ULONG DeckLinkCaptureDevice::Release()
{
	ULONG newRefValue = --m_refCount;
	if (newRefValue == 0)
	{
		delete this;
		return 0;
	}

	return newRefValue;
}

HRESULT DeckLinkCaptureDevice::VideoInputFormatChanged(BMDVideoInputFormatChangedEvents notificationEvents, IDeckLinkDisplayMode* newDisplayMode, BMDDetectedVideoInputFormatFlags detectedSignalFlags)
{
	BMDPixelFormat pixelFormat = m_pixelFormat;
	
	(void)notificationEvents; // unused

	DeviceError error = kNoError;

	// Since recording is configured for a specific video format, stop recording
	if (getDeviceIOState() == kFileIORunning)
		stopRecording();

	if (notificationEvents & bmdVideoInputColorspaceChanged)
	{
		if (detectedSignalFlags & bmdDetectedVideoInputRGB444)
			pixelFormat = bmdFormat8BitBGRA;
		else if (detectedSignalFlags & bmdDetectedVideoInputYCbCr422)
			pixelFormat = bmdFormat10BitYUV;
		else
		{
			error = kInvalidFormatChangedEvent;
			goto bail;
		}
	}
	if (m_detectFormat &&
		((notificationEvents & bmdVideoInputDisplayModeChanged) ||
		 (pixelFormat != m_pixelFormat)))
	{
		// Restart streams if either display mode or colorspace has changed
		m_deckLinkInput->StopStreams();
		
		if (m_deckLinkInput->EnableVideoInput(newDisplayMode->GetDisplayMode(), pixelFormat, bmdVideoInputEnableFormatDetection) != S_OK)
		{
			error = kEnableVideoInputFailed;
			goto bail;
		}

		if (m_deckLinkInput->StartStreams() != S_OK)
		{
			error = kStartCaptureFailed;
			goto bail;
		}

		m_displayMode = newDisplayMode->GetDisplayMode();
		m_pixelFormat = pixelFormat;
		newDisplayMode->GetFrameRate(&m_frameDuration, &m_timeScale);
		
		{
			// Clear video frame properties and refill on next VideoInputFrameArrived callback
			std::lock_guard<std::mutex> lock(m_mutex);
			m_videoFrameProperties.reset(nullptr);
		}

		notifyStatus(kCaptureFormatChanged);
	}

bail:
	if (error)
	{
		disableVideoInput();
		disableAudioInput();
		setState(kDeviceIOIdle);
		notifyError(error);
	}

	return S_OK;
}

HRESULT	DeckLinkCaptureDevice::VideoInputFrameArrived(IDeckLinkVideoInputFrame* videoFrame, IDeckLinkAudioInputPacket* audioPacket)
{
	if (!videoFrame)
		return S_OK;

	DeviceStatus validFrameStatus = (videoFrame->GetFlags() & bmdFrameHasNoInputSource) != 0 ? kCaptureSignalInvalid : kCaptureSignalValid;

	// Notify changes when the input signal becomes valid (or not)
	if (m_lastValidFrameStatus != validFrameStatus)
		notifyStatus(validFrameStatus);

	if (m_deviceState == kDeviceIORunning && validFrameStatus)
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		if (!m_videoFrameProperties)
		{
			m_videoFrameProperties = std::unique_ptr<VideoFrameProperties>(new VideoFrameProperties);
			
			m_videoFrameProperties->width = videoFrame->GetWidth();
			m_videoFrameProperties->height = videoFrame->GetHeight();
			m_videoFrameProperties->pixelFormat = videoFrame->GetPixelFormat();
			m_videoFrameProperties->frameRate = (float)m_timeScale / m_frameDuration;
			
			// Copy the mastering display and content light level data from the underlying CVImageBuffer
			com_ptr<IDeckLinkMacVideoBuffer> macVideoBuffer;
			CVPixelBufferRef cvPixelBuffer;
			
			videoFrame->QueryInterface(IID_IDeckLinkMacVideoBuffer, (void**)macVideoBuffer.releaseAndGetAddressOf());
			if (macVideoBuffer && macVideoBuffer->CreateCVPixelBufferRef((void**)&cvPixelBuffer) == S_OK)
			{
				EOTF detectedEOTF = EOTF::SDR;
				
				m_videoFrameProperties->colorPrimaries = (CFStringRef)CVBufferCopyAttachment(cvPixelBuffer, kCVImageBufferColorPrimariesKey, nullptr);
				m_videoFrameProperties->yCbCrMatrix = (CFStringRef)CVBufferCopyAttachment(cvPixelBuffer, kCVImageBufferYCbCrMatrixKey, nullptr);
				m_videoFrameProperties->transferFunction = (CFStringRef)CVBufferCopyAttachment(cvPixelBuffer, kCVImageBufferTransferFunctionKey, nullptr);
				
				if (CFStringCompare(m_videoFrameProperties->transferFunction, kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ, 0) == kCFCompareEqualTo)
				{
					m_videoFrameProperties->masteringDisplay = (CFDataRef)CVBufferCopyAttachment(cvPixelBuffer, kCVImageBufferMasteringDisplayColorVolumeKey, nullptr);
					
					m_videoFrameProperties->contentLightLevel = (CFDataRef)CVBufferCopyAttachment(cvPixelBuffer, kCVImageBufferContentLightLevelInfoKey, nullptr);
					
					detectedEOTF = EOTF::PQ;
				}
				else if (CFStringCompare(m_videoFrameProperties->transferFunction, kCVImageBufferTransferFunction_ITU_R_2100_HLG, 0) == kCFCompareEqualTo)
				{
					detectedEOTF = EOTF::HLG;
				}
				
				if (detectedEOTF != m_eotf)
				{
					notifyStatus(kCaptureTransferFunctionChanged);
					m_eotf = detectedEOTF;
				}
				
				CVPixelBufferRelease(cvPixelBuffer);
			}
		}
	}
	
	// Check we have a valid frame to write
	if (m_deviceState == kFileIORunning && validFrameStatus)
	{
		// Creating com_ptrs from raw COM objects increments their reference counts
		com_ptr<IDeckLinkVideoInputFrame>	deckLinkVideoFrame(videoFrame);
		com_ptr<IDeckLinkAudioInputPacket>	deckLinkAudioPacket(audioPacket);
		com_ptr<DeckLinkCaptureDevice> self __block;
		self = this;

		// It is important not to block this thread to avoid incoming frames being dropped
		// Hand off video frame writing to a worker queue
		dispatch_async(m_fileWriterQueue, ^{
			self->writeVideoFrame(deckLinkVideoFrame, deckLinkAudioPacket);
		});
	}

	m_lastValidFrameStatus = validFrameStatus;

	return S_OK;
}

HRESULT DeckLinkCaptureDevice::Notify(BMDNotifications topic, uint64_t param1, uint64_t param2)
{
	if (topic == bmdPreferencesChanged)
	{
		int64_t activeVideoInputConnection = bmdVideoConnectionUnspecified;
		if (m_deckLinkConfiguration->GetInt(bmdDeckLinkConfigVideoInputConnection, &activeVideoInputConnection) != S_OK)
			return E_FAIL;
		
		setVideoInputConnection(activeVideoInputConnection);
	}
	else if (topic == bmdStatusChanged)
	{
		if ((BMDDeckLinkStatusID)param1 == bmdDeckLinkStatusDetectedVideoInputColorspace ||
			(BMDDeckLinkStatusID)param1 == bmdDeckLinkStatusDetectedVideoInputDynamicRange)
		{
			// Clear video frame properties and refill on next VideoInputFrameArrived callback
			std::lock_guard<std::mutex> lock(m_mutex);
			m_videoFrameProperties.reset(nullptr);
		}
	}
		
	return S_OK;
}

HRESULT DeckLinkCaptureDevice::ProfileChanging(IDeckLinkProfile *profileToBeActivated, bool streamsWillBeForcedToStop)
{
	if (!profileToBeActivated)
		return E_FAIL;
	
	if (streamsWillBeForcedToStop)
		disable();
	
	return S_OK;
}

HRESULT DeckLinkCaptureDevice::ProfileActivated(IDeckLinkProfile *activatedProfile)
{
	update();
	return S_OK;
}

bool DeckLinkCaptureDevice::init(std::shared_ptr<DeckLinkMediaWriter> mediaWriter)
{
	com_ptr<IDeckLinkInput>					deckLinkInput(IID_IDeckLinkInput, m_deckLink);
	com_ptr<IDeckLinkConfiguration>			deckLinkConfiguration(IID_IDeckLinkConfiguration, m_deckLink);
	com_ptr<IDeckLinkNotification>			deckLinkNotification(IID_IDeckLinkNotification, m_deckLink);
	
	if (!deckLinkInput || !deckLinkConfiguration)
		return false;
	
	m_deckLinkInput = std::move(deckLinkInput);
	
	// Configuration is member variable to ensure settings persist while the device is connected
	m_deckLinkConfiguration = std::move(deckLinkConfiguration);
	
	if (deckLinkNotification)
	{
		deckLinkNotification->Subscribe(bmdPreferencesChanged, this);	// For video input connection changes
		deckLinkNotification->Subscribe(bmdStatusChanged, this);		// For colorspace and dynamic range changes
	}
	
	com_ptr<IDeckLinkProfileManager> profileManager(IID_IDeckLinkProfileManager, m_deckLink);
	if (profileManager)
		profileManager->SetCallback(this);
	
	update();

	// Reset video format parameters and set on first valid captured frame
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		m_videoFrameProperties.reset(nullptr);
	}
	
	m_mediaWriter = mediaWriter;
	m_init = true;

	return m_init;
}

bool DeckLinkCaptureDevice::update()
{
	com_ptr<IDeckLinkProfileAttributes>	deckLinkAttributes(IID_IDeckLinkProfileAttributes, m_deckLink);
	
	if (!deckLinkAttributes)
		return false;
	
	if (deckLinkAttributes->GetInt(BMDDeckLinkVideoInputConnections, &m_videoInputConnections) != S_OK)
		m_videoInputConnections = bmdVideoConnectionUnspecified;
	
	if (m_deckLinkConfiguration->GetInt(bmdDeckLinkConfigVideoInputConnection, &m_activeVideoInputConnection) != S_OK)
		m_activeVideoInputConnection = bmdVideoConnectionUnspecified;
	
	int64_t intVal = 0;
	if (deckLinkAttributes->GetInt(BMDDeckLinkDuplex, &intVal) != S_OK)
		return E_FAIL;
	
	m_isAvailable = (intVal != bmdDuplexInactive);
	
	notifyStatus(kDeviceProfileChanged);
	return true;
}

CFStringRef DeckLinkCaptureDevice::displayName() const
{
	return m_displayName;
}

int64_t DeckLinkCaptureDevice::getDeviceID() const
{
	return m_deviceID;
}

DeviceIOState DeckLinkCaptureDevice::getDeviceIOState() const
{
	return m_deviceState;
}

void DeckLinkCaptureDevice::setErrorListener(const DeviceErrorOccurredFunc& func)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	m_errorListener = func;
}

void DeckLinkCaptureDevice::setStatusListener(const DeviceStatusUpdateFunc& func)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	m_statusListener = func;
}

void DeckLinkCaptureDevice::notifyStatus(DeviceStatus status)
{
	if (m_statusListener)
		m_statusListener(com_ptr<DeckLinkCaptureDevice>(this), status);
}

void DeckLinkCaptureDevice::notifyError(DeviceError error)
{
	if (m_errorListener)
		m_errorListener(com_ptr<DeckLinkCaptureDevice>(this), error);
}

void DeckLinkCaptureDevice::capture(com_ptr<IDeckLinkScreenPreviewCallback> previewCallback, BMDDisplayMode displayMode)
{
	DeviceError			error			= kNoError;
	BMDVideoInputFlags	videoInputFlags	= m_detectFormat ? bmdVideoInputEnableFormatDetection : bmdVideoInputFlagDefault;
	com_ptr<IDeckLinkDisplayMode> deckLinkDisplayMode;

	if (!m_isAvailable || m_deviceState != kDeviceIOIdle)
		return;
	
	m_deckLinkInput->SetScreenPreviewCallback(previewCallback.get());
	m_deckLinkInput->SetCallback(this);

	m_lastValidFrameStatus = kCaptureSignalUnknown;

	if (m_videoInputEnabled)
		disableVideoInput();
	
	enableVideoInput(displayMode, m_pixelFormat, videoInputFlags);
	if (!m_videoInputEnabled)
	{
		error = kEnableVideoInputFailed;
		goto bail;
	}

	if (m_audioInputEnabled)
		disableAudioInput();
	
	enableAudioInput(bmdAudioSampleRate48kHz, m_mediaWriter->audioBitsPerSample(), m_mediaWriter->audioChannelCount());
	if (!m_audioInputEnabled)
	{
		error = kEnableAudioInputFailed;
		goto bail;
	}

	m_displayMode = displayMode;

	if (m_deckLinkInput->StartStreams() != S_OK)
	{
		error = kStartCaptureFailed;
		goto bail;
	}

	if (m_deckLinkInput->GetDisplayMode(m_displayMode, deckLinkDisplayMode.releaseAndGetAddressOf()) != S_OK || !deckLinkDisplayMode)
		return;
	
	if (deckLinkDisplayMode->GetFrameRate(&m_frameDuration, &m_timeScale) != S_OK)
		return;
	
	setState(kDeviceIORunning);

bail:
	if (error)
	{
		disableVideoInput();
		disableAudioInput();
		setState(kDeviceIOIdle);
		notifyError(error);
	}
}

void DeckLinkCaptureDevice::record(const std::string& filePath, const bool useHEVCCodec)
{
	if (m_deviceState != kDeviceIORunning)
		return;
	
	if (!m_init || m_displayMode == bmdModeUnknown)
	{
		setState(kDeviceIOError);
		return;
	}

	// Initialize the media writer for the active display mode
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		if (!m_mediaWriter->init(filePath, useHEVCCodec, m_videoFrameProperties, m_timeScale))
		{
			setState(kDeviceIORunning);
			return;
		}
	}
	
	setState(kFileIORunning);
}

void DeckLinkCaptureDevice::stopRecording(bool save)
{
	if (m_deviceState != kFileIORunning || !m_deckLinkInput)
		return;

	if (m_mediaWriter)
		m_mediaWriter->complete(save);

	setState(kDeviceIORunning);

	notifyStatus(kRecordingComplete);
}

void DeckLinkCaptureDevice::disable()
{
	com_ptr<IDeckLinkNotification> deckLinkNotification(IID_IDeckLinkNotification, m_deckLink);
	if (deckLinkNotification)
	{
		deckLinkNotification->Unsubscribe(bmdPreferencesChanged, this);
		deckLinkNotification->Unsubscribe(bmdStatusChanged, this);
	}
	
	com_ptr<IDeckLinkProfileManager> profileManager(IID_IDeckLinkProfileManager, m_deckLink);
	if (profileManager)
		profileManager->SetCallback(nullptr);
	
	if (m_deviceState == kDeviceIOIdle)
		return;

	stopRecording();
	disableVideoInput();
	disableAudioInput();

	setState(kDeviceIOIdle);
}

void DeckLinkCaptureDevice::setVideoInputConnection(int64_t connection)
{
	if (connection == m_activeVideoInputConnection)
		return;
	
	if (m_deckLinkConfiguration->SetInt(bmdDeckLinkConfigVideoInputConnection, connection) == S_OK)
	{
		// For simplicity capture embedded audio where possible
		m_deckLinkConfiguration->SetInt(bmdDeckLinkConfigAudioInputConnection, bmdAudioConnectionEmbedded);
		
		m_activeVideoInputConnection = connection;
		notifyStatus(kDeviceVideoInputChanged);
	}
}

BMDDisplayMode DeckLinkCaptureDevice::activeDisplayMode() const
{
	return m_displayMode;
}

bool DeckLinkCaptureDevice::formatAutoDetect() const
{
	return m_detectFormat;
}

bool DeckLinkCaptureDevice::supportsFormatAutoDetect() const
{
	return m_supportsFormatDetection;
}

int64_t DeckLinkCaptureDevice::videoInputConnections() const
{
	return m_videoInputConnections;
}

int64_t DeckLinkCaptureDevice::activeVideoInputConnection() const
{
	return m_activeVideoInputConnection;
}

EOTF DeckLinkCaptureDevice::activeTransferFunction() const
{
	return m_eotf;
}

void DeckLinkCaptureDevice::queryDisplayModes(DeckLinkDisplayModeQueryFunc func)
{
	com_ptr<IDeckLinkDisplayModeIterator>	displayModeIterator;
	com_ptr<IDeckLinkDisplayMode>			displayMode;

	std::lock_guard<std::mutex> lock(m_mutex);

	if (m_deckLinkInput->GetDisplayModeIterator(displayModeIterator.releaseAndGetAddressOf()) != S_OK)
		return;

	while (displayModeIterator->Next(displayMode.releaseAndGetAddressOf()) == S_OK)
		func(displayMode);
}

std::string DeckLinkCaptureDevice::filePath() const
{
	if (!m_mediaWriter)
		return std::string();

	return m_mediaWriter->filePath();
}

void DeckLinkCaptureDevice::setState(DeviceIOState deviceState)
{
	m_deviceState = deviceState;
	notifyStatus(kDeviceStateChanged);
}

void DeckLinkCaptureDevice::setFormatAutoDetect(bool enabled)
{
	m_detectFormat = enabled;
}

void DeckLinkCaptureDevice::enableVideoInput(BMDDisplayMode displayMode, BMDPixelFormat pixelFormat, BMDVideoInputFlags flags)
{
	if (m_videoInputEnabled)
		return;

	bool displayModeSupported = true;
	
	if ((m_deckLinkInput->DoesSupportVideoMode((BMDVideoConnection)m_activeVideoInputConnection, displayMode, pixelFormat, bmdNoVideoInputConversion, bmdSupportedVideoModeDefault, NULL, &displayModeSupported) != S_OK)
		|| !displayModeSupported)
		return;

	if (m_deckLinkInput->EnableVideoInput(displayMode, pixelFormat, flags) == S_OK)
		m_videoInputEnabled = true;
}

void DeckLinkCaptureDevice::disableVideoInput()
{
	if (m_videoInputEnabled)
	{
		m_deckLinkInput->StopStreams();
		m_deckLinkInput->DisableVideoInput();
		m_deckLinkInput->SetCallback(nullptr);
		m_deckLinkInput->SetScreenPreviewCallback(nullptr);

		m_videoInputEnabled = false;
	}
}

void DeckLinkCaptureDevice::enableAudioInput(BMDAudioSampleRate sampleRate, BMDAudioSampleType sampleType, uint32_t channelCount)
{
	if (!m_audioInputEnabled && m_deckLinkInput->EnableAudioInput(sampleRate, sampleType, channelCount) == S_OK)
		m_audioInputEnabled = true;
}

void DeckLinkCaptureDevice::disableAudioInput()
{
	if (m_audioInputEnabled)
	{
		m_deckLinkInput->DisableAudioInput();
		m_audioInputEnabled = false;
	}
}

bool DeckLinkCaptureDevice::writeVideoFrame(com_ptr<IDeckLinkVideoInputFrame> deckLinkFrame, com_ptr<IDeckLinkAudioInputPacket> audioPacket)
{
	BMDTimeValue					frameTime	= 0;
	BMDTimeValue					duration	= 0;
	com_ptr<IDeckLinkVideoFrame>	videoFrame(IID_IDeckLinkVideoFrame, deckLinkFrame);

	if (!videoFrame)
	{
		notifyError(kMediaFileWriteFailed);
		return false;
	}
	deckLinkFrame->GetStreamTime(&frameTime, &duration, m_timeScale);

	m_mediaWriter->writeFrame(videoFrame, frameTime, audioPacket, std::bind(&DeckLinkCaptureDevice::checkWriteResult, this, std::placeholders::_1));
	
	return true;
}

void DeckLinkCaptureDevice::checkWriteResult(WriteResult writeResult)
{
	switch (writeResult)
	{
		case kFrameDropped:
			notifyError(kMediaFileFrameDropped);
			break;
			
		case kFrameError:
			notifyError(kMediaFileWriteFailed);
			break;

		case kFrameComplete:
		case kFrameFlushed:
		default:
			break;
	}
}

bool DeckLinkCaptureDevice::isAvailable() const
{
	return m_isAvailable;
}
