/* -LICENSE-START-
** Copyright (c) 2023 Blackmagic Design
**  
** Permission is hereby granted, free of charge, to any person or organization 
** obtaining a copy of the software and accompanying documentation (the 
** "Software") to use, reproduce, display, distribute, sub-license, execute, 
** and transmit the Software, and to prepare derivative works of the Software, 
** and to permit third-parties to whom the Software is furnished to do so, in 
** accordance with:
** 
** (1) if the Software is obtained from Blackmagic Design, the End User License 
** Agreement for the Software Development Kit ("EULA") available at 
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
** 
** (2) if the Software is obtained from any third party, such licensing terms 
** as notified by that third party,
** 
** and all subject to the following:
** 
** (3) the copyright notices in the Software and this entire statement, 
** including the above license grant, this restriction and the following 
** disclaimer, must be included in all copies of the Software, in whole or in 
** part, and all derivative works of the Software, unless such copies or 
** derivative works are solely in the form of machine-executable object code 
** generated by a source language processor.
** 
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
** DEALINGS IN THE SOFTWARE.
** 
** A copy of the Software is available free of charge at 
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
** 
** -LICENSE-END-
*/

#include "VideoFrame3DExtensions.h"
#include "com_ptr.h"

#include <stdexcept>

VideoFrame3DExtensions::Provider::Provider(IDeckLinkMutableVideoFrame* parentFrame, IDeckLinkVideoFrame* rightFrame) :
	m_refCount(1),
	m_parentFrame(parentFrame),
	m_rightFrame(rightFrame)
{
}

HRESULT VideoFrame3DExtensions::Provider::QueryInterface(REFIID iid, LPVOID* ppv)
{
	// Return an interface that, unlike the provider, *does* add a ref to m_parentFrame until released
	com_ptr<VideoFrame3DExtensions> videoFrame3DExtensions = make_com_ptr<VideoFrame3DExtensions>(m_parentFrame, m_rightFrame);
	return videoFrame3DExtensions->QueryInterface(iid, ppv);
}

ULONG VideoFrame3DExtensions::Provider::AddRef()
{
	return ++m_refCount;
}

ULONG VideoFrame3DExtensions::Provider::Release()
{
	auto refs = --m_refCount;
	if (!refs)
		delete this;
	return refs;
}

VideoFrame3DExtensions::VideoFrame3DExtensions(IDeckLinkMutableVideoFrame* owner, com_ptr<IDeckLinkVideoFrame>& right) :
	m_owner(owner),
	m_frameRight(right),
	m_refCount(1)
{
	if (! m_owner || ! m_frameRight)
		throw std::invalid_argument("missing owner or right frame");
}

HRESULT VideoFrame3DExtensions::QueryInterface(REFIID iid, LPVOID *ppv)
{
	if (memcmp(&iid, &IID_IDeckLinkVideoFrame3DExtensions, sizeof(REFIID)) == 0)
	{
		*ppv = static_cast<IDeckLinkVideoFrame3DExtensions*>(this);
		AddRef();
		return S_OK;
	}
	else
	{
		// Since we used m_frameLeft->AttachInterface(), assumed IUnknown comes from m_owner too
		// so that QueryInterface in both directions is symmmetrical
		return m_owner->QueryInterface(iid, ppv);
	}
}

ULONG VideoFrame3DExtensions::AddRef(void)
{
	return ++m_refCount;
}

ULONG VideoFrame3DExtensions::Release(void)
{
	ULONG newRefValue = --m_refCount;
	if (newRefValue == 0)
		delete this;
	
	return newRefValue;
}

BMDVideo3DPackingFormat VideoFrame3DExtensions::Get3DPackingFormat(void)
{
	return bmdVideo3DPackingLeftOnly;
}

HRESULT VideoFrame3DExtensions::GetFrameForRightEye(IDeckLinkVideoFrame** rightEyeFrame)
{
	return m_frameRight->QueryInterface(IID_IDeckLinkVideoFrame, (void**)rightEyeFrame);
}
