/* -LICENSE-START-
** Copyright (c) 2018 Blackmagic Design
**  
** Permission is hereby granted, free of charge, to any person or organization 
** obtaining a copy of the software and accompanying documentation (the 
** "Software") to use, reproduce, display, distribute, sub-license, execute, 
** and transmit the Software, and to prepare derivative works of the Software, 
** and to permit third-parties to whom the Software is furnished to do so, in 
** accordance with:
** 
** (1) if the Software is obtained from Blackmagic Design, the End User License 
** Agreement for the Software Development Kit ("EULA") available at 
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
** 
** (2) if the Software is obtained from any third party, such licensing terms 
** as notified by that third party,
** 
** and all subject to the following:
** 
** (3) the copyright notices in the Software and this entire statement, 
** including the above license grant, this restriction and the following 
** disclaimer, must be included in all copies of the Software, in whole or in 
** part, and all derivative works of the Software, unless such copies or 
** derivative works are solely in the form of machine-executable object code 
** generated by a source language processor.
** 
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
** DEALINGS IN THE SOFTWARE.
** 
** A copy of the Software is available free of charge at 
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
** 
** -LICENSE-END-
*/

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <pthread.h>
#include <unistd.h>
#include "Config.h"
#include "com_ptr.h"

BMDConfig::BMDConfig() :
	m_deckLinkIndex(-1),
	m_displayModeIndex(-1),
	m_audioChannels(2),
	m_audioSampleDepth(16),
	m_outputFlags(bmdVideoOutputFlagDefault),
	m_pixelFormat(bmdFormat8BitYUV),
	m_output444(false),
	m_deckLinkName(),
	m_displayModeName()
{
}

BMDConfig::~BMDConfig()
{
	if (m_deckLinkName)
		free(m_deckLinkName);

	if (m_displayModeName)
		free(m_displayModeName);
}

bool BMDConfig::ParseArguments(int argc,  char** argv)
{
	int		ch;
	bool	displayHelp = false;

	while ((ch = getopt(argc, argv, "d:?h3c:s:f:a:m:n:p:t:")) != -1)
	{
		switch (ch)
		{
			case 'd':
				m_deckLinkIndex = atoi(optarg);
				break;

			case 'm':
				m_displayModeIndex = atoi(optarg);
				break;

			case 'c':
				m_audioChannels = atoi(optarg);
				if (m_audioChannels != 2 &&
					m_audioChannels != 8 &&
					m_audioChannels != 16)
				{
					fprintf(stderr, "Invalid argument: Audio Channels must be either 2, 8 or 16\n");
					return false;
				}
				break;

			case 's':
				m_audioSampleDepth = atoi(optarg);
				if (m_audioSampleDepth != 16 && m_audioSampleDepth != 32)
				{
					fprintf(stderr, "Invalid argument: Audio Sample Depth must be either 16 bits or 32 bits\n");
					return false;
				}
				break;

			case 'p':
				switch(atoi(optarg))
				{
					case 0: m_pixelFormat = bmdFormat8BitYUV;  m_output444 = false; break;
					case 1: m_pixelFormat = bmdFormat10BitYUV; m_output444 = false; break;
					case 2: m_pixelFormat = bmdFormat10BitRGB; m_output444 = true;  break;
					default:
						fprintf(stderr, "Invalid argument: Pixel format %d is not valid", atoi(optarg));
						return false;
				}
				break;

			case '3':
				m_outputFlags |= bmdVideoOutputDualStream3D;
				break;

			case '?':
			case 'h':
				displayHelp = true;
		}
	}

	if (displayHelp)
	{
		DisplayUsage();
		return true;
	}

	if (m_deckLinkIndex < 0)
	{
		fprintf(stderr, "You must select a device\n");
		return false;
	}

	if (m_displayModeIndex < 0)
	{
		fprintf(stderr, "You must select a display mode\n");
		return false;
	}

	// Get device, its active state and display mode names
	com_ptr<IDeckLink> deckLink = GetSelectedDeckLink();
	if (!deckLink)
	{
		fprintf(stderr, "Invalid device selected\n");
		return false;
	}

	if (!IsDeviceActive(deckLink))
	{
		fprintf(stderr, "Selected device is inactive\n");
		return false;
	}

	com_ptr<IDeckLinkDisplayMode> displayMode = GetSelectedDeckLinkDisplayMode(deckLink);
	if (displayMode)
	{
		displayMode->GetName((const char**)&m_displayModeName);
	}
	else
	{
		m_displayModeName = strdup("Invalid");
	}

	deckLink->GetDisplayName((const char**)&m_deckLinkName);

	return true;
}

void BMDConfig::DisplayUsage()
{
	HRESULT							result = E_FAIL;
	com_ptr<IDeckLinkIterator>		deckLinkIterator;
	com_ptr<IDeckLinkDisplayModeIterator>	displayModeIterator = NULL;
	com_ptr<IDeckLink>				deckLink = NULL;
	com_ptr<IDeckLink>				deckLinkSelected = NULL;
	int								deckLinkCount = 0;
	char*							deckLinkName;
	com_ptr<IDeckLinkOutput>		deckLinkOutput;
	com_ptr<IDeckLinkDisplayMode>	displayMode;
	int								displayModeCount = 0;
	char*							displayModeName;

	fprintf(stderr,
		"Usage: TestPattern -d <device id> -m <mode id> [OPTIONS]\n"
		"\n"
		"    -d <device id>:\n"
	);

	// Loop through all available devices
	deckLinkIterator = CreateDeckLinkIteratorInstance();
	while (deckLinkIterator->Next(deckLink.releaseAndGetAddressOf()) == S_OK)
	{
		if (!IsPlaybackDevice(deckLink))
		{
			// Only display devices that support playback.
			continue;
		}
		
		char *displayName;
		result = deckLink->GetDisplayName((const char**)&displayName);
		if (result == S_OK)
		{
			fprintf(stderr,
				"        %2d: %s%s%s\n",
				deckLinkCount,
				displayName,
				IsDeviceActive(deckLink) ? "" : " (inactive)",
				deckLinkCount == m_deckLinkIndex ? " (selected)" : ""
			);

			free(displayName);
		}

		if (deckLinkCount == m_deckLinkIndex)
			deckLinkSelected = deckLink;

		++deckLinkCount;
	}

	if (deckLinkCount == 0)
		fprintf(stderr, "        No DeckLink devices supporting output found. Is the driver loaded?\n");

	deckLinkName = NULL;

	if (deckLinkSelected)
		deckLinkSelected->GetDisplayName((const char**)&deckLinkName);

	fprintf(stderr,
		"    -m <mode id>: (%s)\n",
		deckLinkName ? deckLinkName : ""
	);

	if (deckLinkName != NULL)
		free(deckLinkName);

	// Loop through all available display modes on the delected DeckLink device
	if (!deckLinkSelected)
	{
		fprintf(stderr, "        No DeckLink device selected\n");
		goto bail;
	}

	deckLinkOutput = com_ptr<IDeckLinkOutput>(IID_IDeckLinkOutput, deckLinkSelected);
	if (!deckLinkOutput)
		goto bail;

	result = deckLinkOutput->GetDisplayModeIterator(displayModeIterator.releaseAndGetAddressOf());
	if (result != S_OK)
		goto bail;

	while (displayModeIterator->Next(displayMode.releaseAndGetAddressOf()) == S_OK)
	{
		result = displayMode->GetName((const char **)&displayModeName);
		if (result == S_OK)
		{
			BMDTimeValue frameRateDuration;
			BMDTimeValue frameRateScale;

			displayMode->GetFrameRate(&frameRateDuration, &frameRateScale);

			fprintf(stderr,
				"        %2d:  %-20s \t %li x %li \t %g FPS\n",
				displayModeCount,
				displayModeName,
				displayMode->GetWidth(),
				displayMode->GetHeight(),
				(double)frameRateScale / (double)frameRateDuration
			);

			free(displayModeName);
		}

		++displayModeCount;
	}

bail:
	fprintf(stderr,
		"    -p <pixelformat>\n"
		"         0:  8 bit YUV (4:2:2) (default)\n"
		"         1:  10 bit YUV (4:2:2)\n"
		"         2:  10 bit RGB (4:4:4)\n"
		"    -c <channels>        Audio Channels (2, 8 or 16 - default is 2)\n"
		"    -s <depth>           Audio Sample Depth (16 or 32 - default is 16)\n"
		"    -3                   Playback Stereoscopic 3D (Requires 3D Hardware support)\n"
		"\n"
		"Output a test pattern eg:\n"
		"\n"
		"    TestPattern -d 0 -m 2 \n"
	);
}

void BMDConfig::DisplayConfiguration()
{
	fprintf(stderr, "Outputting with the following configuration:\n"
		" - Playback device: %s\n"
		" - Video mode: %s %s\n"
		" - Pixel format: %s\n"
		" - Audio channels: %u\n"
		" - Audio sample depth: %u bit \n",
		m_deckLinkName,
		m_displayModeName,
		(m_outputFlags & bmdVideoOutputDualStream3D) ? "3D" : "",
		GetPixelFormatName(m_pixelFormat),
		m_audioChannels,
		m_audioSampleDepth
	);
}

com_ptr<IDeckLink> BMDConfig::GetSelectedDeckLink()
{
	HRESULT						result;
	com_ptr<IDeckLink>			deckLink;
	com_ptr<IDeckLinkIterator>	deckLinkIterator;
	int					i = 0;

	deckLinkIterator = CreateDeckLinkIteratorInstance();
	if (!deckLinkIterator)
	{
		fprintf(stderr, "This application requires the DeckLink drivers installed.\n");
		return NULL;
	}

	while((result = deckLinkIterator->Next(deckLink.releaseAndGetAddressOf())) == S_OK)
	{
		// Skip over devices that don't support playback
		if (IsPlaybackDevice(deckLink))
		{
			if (m_deckLinkIndex == i++)
				break;
		}

	}

	if (result != S_OK)
		return NULL;

	return deckLink;
}

com_ptr<IDeckLinkDisplayMode> BMDConfig::GetSelectedDeckLinkDisplayMode(com_ptr<IDeckLink>& deckLink)
{
	HRESULT									result;
	com_ptr<IDeckLinkDisplayMode>			displayMode = NULL;
	com_ptr<IDeckLinkOutput>				deckLinkOutput;
	com_ptr<IDeckLinkDisplayModeIterator>	displayModeIterator = NULL;
	int										i = 0;

	deckLinkOutput = com_ptr<IDeckLinkOutput>(IID_IDeckLinkOutput, deckLink);
	if (!deckLinkOutput)
		return NULL;

	result = deckLinkOutput->GetDisplayModeIterator(displayModeIterator.releaseAndGetAddressOf());
	if (result != S_OK)
		return NULL;

	while ((result = displayModeIterator->Next(displayMode.releaseAndGetAddressOf())) == S_OK)
	{
		if (m_displayModeIndex == i++)
			break;
	}

	return displayMode;
}

const char* BMDConfig::GetPixelFormatName(BMDPixelFormat pixelFormat)
{
	switch (pixelFormat)
	{
		case bmdFormat8BitYUV:
			return "8 bit YUV (4:2:2)";
		case bmdFormat10BitYUV:
			return "10 bit YUV (4:2:2)";
		case bmdFormat10BitRGB:
			return "10 bit RGB (4:4:4)";
	}
	return "unknown";
}

bool BMDConfig::IsDeviceActive(com_ptr<IDeckLink>& deckLink)
{
	com_ptr<IDeckLinkProfileAttributes> deckLinkAttributes(IID_IDeckLinkProfileAttributes, deckLink);
	if (!deckLinkAttributes)
		return false;

	int64_t duplexMode;
	if (deckLinkAttributes->GetInt(BMDDeckLinkDuplex, &duplexMode) != S_OK)
		duplexMode = (int64_t)bmdDuplexInactive;

	return (BMDDuplexMode)duplexMode != bmdDuplexInactive;
}

bool BMDConfig::IsPlaybackDevice(com_ptr<IDeckLink>& deckLink)
{
	com_ptr<IDeckLinkProfileAttributes> deckLinkAttributes(IID_IDeckLinkProfileAttributes, deckLink);

	int64_t ioSupport;
	if (deckLinkAttributes->GetInt(BMDDeckLinkVideoIOSupport, &ioSupport) != S_OK)
		ioSupport = 0;

	return ((BMDVideoIOSupport)ioSupport & bmdDeviceSupportsPlayback) != 0;
}

