/* -LICENSE-START-
** Copyright (c) 2018 Blackmagic Design
**  
** Permission is hereby granted, free of charge, to any person or organization 
** obtaining a copy of the software and accompanying documentation (the 
** "Software") to use, reproduce, display, distribute, sub-license, execute, 
** and transmit the Software, and to prepare derivative works of the Software, 
** and to permit third-parties to whom the Software is furnished to do so, in 
** accordance with:
** 
** (1) if the Software is obtained from Blackmagic Design, the End User License 
** Agreement for the Software Development Kit ("EULA") available at 
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
** 
** (2) if the Software is obtained from any third party, such licensing terms 
** as notified by that third party,
** 
** and all subject to the following:
** 
** (3) the copyright notices in the Software and this entire statement, 
** including the above license grant, this restriction and the following 
** disclaimer, must be included in all copies of the Software, in whole or in 
** part, and all derivative works of the Software, unless such copies or 
** derivative works are solely in the form of machine-executable object code 
** generated by a source language processor.
** 
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
** DEALINGS IN THE SOFTWARE.
** 
** A copy of the Software is available free of charge at 
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
** 
** -LICENSE-END-
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <libgen.h>
#include <signal.h>
#include <pthread.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <arpa/inet.h>

#include "TestPattern.h"
#include "VideoFrame3D.h"
#include "com_ptr.h"

pthread_mutex_t			sleepMutex;
pthread_cond_t			sleepCond;
bool					do_exit = false;

const unsigned long		kAudioWaterlevel = 48000;

void sigfunc(int signum)
{
	if (signum == SIGINT || signum == SIGTERM) {
		do_exit = true;
	}
	pthread_cond_signal(&sleepCond);
}

int main(int argc, char *argv[])
{
	com_ptr<TestPattern>	generator = NULL;

	pthread_mutex_init(&sleepMutex, NULL);
	pthread_cond_init(&sleepCond, NULL);

	signal(SIGINT, sigfunc);
	signal(SIGTERM, sigfunc);
	signal(SIGHUP, sigfunc);

	BMDConfig config;
	if (!config.ParseArguments(argc, argv))
	{
		config.DisplayUsage();
		return 1;
	}

	generator = make_com_ptr<TestPattern>(&config);

	if (!generator->Run())
		return 1;

	// All Okay.
	return 0;
}

TestPattern::~TestPattern()
{
}

TestPattern::TestPattern(BMDConfig *config) :
	m_refCount(1),
	m_config(config),
	m_running(false),
	m_deckLink(),
	m_deckLinkOutput(),
	m_deckLinkConfiguration(),
	m_displayMode(),
	m_videoFrameBlack(),
	m_videoFrameBars(),
	m_outputSignal(kOutputSignalDrop),
	m_audioBuffer(),
	m_audioSampleRate(bmdAudioSampleRate48kHz)
{
}

bool TestPattern::Run()
{
	HRESULT		result;
	char*		displayModeName = NULL;

	// Get the DeckLink device
	m_deckLink = m_config->GetSelectedDeckLink();
	if (m_deckLink == NULL)
	{
		fprintf(stderr, "Unable to get DeckLink output device %u\n", m_config->m_deckLinkIndex);
		return false;
	}

	// Get the output (display) interface of the DeckLink device
	m_deckLinkOutput = com_ptr<IDeckLinkOutput>(IID_IDeckLinkOutput, m_deckLink);
	if (!m_deckLinkOutput)
		return false;

	// Get the configuration interface of the DeckLink device
	m_deckLinkConfiguration = com_ptr<IDeckLinkConfiguration>(IID_IDeckLinkConfiguration, m_deckLink);
	if (!m_deckLinkConfiguration)
		return false;

	// Get the display mode
	m_displayMode = m_config->GetSelectedDeckLinkDisplayMode(m_deckLink);
	if (m_displayMode == NULL)
	{
		fprintf(stderr, "Unable to get display mode %d\n", m_config->m_displayModeIndex);
		return false;
	}

	// Check for 3D support on display mode
	if ((m_config->m_outputFlags & bmdVideoOutputDualStream3D) && !(m_displayMode->GetFlags() & bmdDisplayModeSupports3D))
	{
		// Get display mode name
		result = m_displayMode->GetName((const char**)&displayModeName);
		if (result != S_OK)
		{
			displayModeName = (char *)malloc(32);
			snprintf(displayModeName, 32, "[index %d]", m_config->m_displayModeIndex);
		}

		fprintf(stderr, "The display mode %s is not supported with 3D\n", displayModeName);
		free(displayModeName);
		return false;
	}

	m_config->DisplayConfiguration();

	// Provide this class as a delegate to the audio and video output interfaces
	m_deckLinkOutput->SetScheduledFrameCompletionCallback(this);
	m_deckLinkOutput->SetAudioCallback(this);

	// Start.
	while (!do_exit)
	{
		StartRunning();
		fprintf(stderr, "Starting playback\n");

		pthread_mutex_lock(&sleepMutex);
		pthread_cond_wait(&sleepCond, &sleepMutex);
		pthread_mutex_unlock(&sleepMutex);

		fprintf(stderr, "Stopping playback\n");
		StopRunning();
	}

	printf("\n");
	return true;
}

void TestPattern::StartRunning()
{
	HRESULT					result;
	unsigned long			audioSamplesPerFrame;

	m_frameWidth = m_displayMode->GetWidth();
	m_frameHeight = m_displayMode->GetHeight();
	m_displayMode->GetFrameRate(&m_frameDuration, &m_frameTimescale);

	// Calculate the number of frames per second, rounded up to the nearest integer.  For example, for NTSC (29.97 FPS), framesPerSecond == 30.
	m_framesPerSecond = (unsigned long)((m_frameTimescale + (m_frameDuration-1))  /  m_frameDuration);

	// Set the output to 444 if RGB mode is selected
	result = m_deckLinkConfiguration->SetFlag(bmdDeckLinkConfig444SDIVideoOutput, m_config->m_output444);
	// If a device without SDI output is used (eg Intensity Pro 4K), then SetFlags will return E_NOTIMPL
	if ((result != S_OK) && (result != E_NOTIMPL))
	{
		fprintf(stderr, "Failed to write to 444 output configuration flag\n");
		goto bail;
	}

	// Set the video output mode
	result = m_deckLinkOutput->EnableVideoOutput(m_displayMode->GetDisplayMode(), m_config->m_outputFlags);
	if (result != S_OK)
	{
		fprintf(stderr, "Failed to enable video output. Is another application using the card?\n");
		goto bail;
	}

	// Set the audio output mode
	result = m_deckLinkOutput->EnableAudioOutput(bmdAudioSampleRate48kHz, m_config->m_audioSampleDepth, m_config->m_audioChannels, bmdAudioOutputStreamContinuous);
	if (result != S_OK)
	{
		fprintf(stderr, "Failed to enable audio output\n");
		goto bail;
	}

	// Generate one second of audio
	m_audioBufferSampleLength = (unsigned long)((m_framesPerSecond * m_audioSampleRate * m_frameDuration) / m_frameTimescale);
	m_audioBuffer = valloc(m_audioBufferSampleLength * m_config->m_audioChannels * (m_config->m_audioSampleDepth / 8));

	if (m_audioBuffer == NULL)
	{
		fprintf(stderr, "Failed to allocate audio buffer memory\n");
		goto bail;
	}

	// Zero the buffer (interpreted as audio silence)
	memset(m_audioBuffer, 0x0, (m_audioBufferSampleLength * m_config->m_audioChannels * m_config->m_audioSampleDepth / 8));
	audioSamplesPerFrame = (unsigned long)((m_audioSampleRate * m_frameDuration) / m_frameTimescale);

	if (m_outputSignal == kOutputSignalPip)
		FillSine(m_audioBuffer, audioSamplesPerFrame, m_config->m_audioChannels, m_config->m_audioSampleDepth);
	else
		FillSine((void*)((unsigned long)m_audioBuffer + (audioSamplesPerFrame * m_config->m_audioChannels * m_config->m_audioSampleDepth / 8)), (m_audioBufferSampleLength - audioSamplesPerFrame), m_config->m_audioChannels, m_config->m_audioSampleDepth);

	// Generate a frame of black
	if (CreateFrame(m_videoFrameBlack, FillBlack) != S_OK)
		goto bail;

	if (m_config->m_outputFlags & bmdVideoOutputDualStream3D)
	{
		com_ptr<IDeckLinkMutableVideoFrame>	rightMutableVideoFrame;
		if (CreateFrame(rightMutableVideoFrame, FillBlack) != S_OK)
			goto bail;
		com_ptr<IDeckLinkVideoFrame> rightVideoFrame(IID_IDeckLinkVideoFrame, rightMutableVideoFrame);

		com_ptr<VideoFrame3D::Provider> provider = make_com_ptr<VideoFrame3D::Provider>(m_videoFrameBlack.get(), rightVideoFrame);
		result = m_videoFrameBlack->SetInterfaceProvider(IID_IDeckLinkVideoFrame3DExtensions, provider.get());
		if (FAILED(result))
			goto bail;
	}

	// Generate a frame of colour bars
	if (CreateFrame(m_videoFrameBars, FillForwardColourBars) != S_OK)
		goto bail;

	if (m_config->m_outputFlags & bmdVideoOutputDualStream3D)
	{
		com_ptr<IDeckLinkMutableVideoFrame>	rightMutableVideoFrame;
		if (CreateFrame(rightMutableVideoFrame, FillReverseColourBars) != S_OK)
			goto bail;
		com_ptr<IDeckLinkVideoFrame> rightVideoFrame(IID_IDeckLinkVideoFrame, rightMutableVideoFrame);

		com_ptr<VideoFrame3D::Provider> provider = make_com_ptr<VideoFrame3D::Provider>(m_videoFrameBars.get(), rightVideoFrame);
		result = m_videoFrameBars->SetInterfaceProvider(IID_IDeckLinkVideoFrame3DExtensions, provider.get());
		if (FAILED(result))
			goto bail;
	}

	// Begin video preroll by scheduling a second of frames in hardware
	m_totalFramesScheduled = 0;
	m_totalFramesDropped = 0;
	m_totalFramesDisplayedLate = 0;
	m_totalFramesCompleted = 0;
	for (unsigned i = 0; i < m_framesPerSecond; i++)
		ScheduleNextFrame(true);

	// Begin audio preroll.  This will begin calling our audio callback, which will start the DeckLink output stream.
	m_audioBufferOffset = 0;
	if (m_deckLinkOutput->BeginAudioPreroll() != S_OK)
	{
		fprintf(stderr, "Failed to begin audio preroll\n");
		goto bail;
	}

	{
		std::lock_guard<std::mutex> guard(m_mutex);
		m_running = true;
	}
	
	return;

bail:
	// *** Error-handling code.  Cleanup any resources that were allocated. *** //
	StopRunning();
}

void TestPattern::StopRunning()
{
	// Stop the audio and video output streams immediately
	m_deckLinkOutput->StopScheduledPlayback(0, NULL, 0);

	{
		// Wait for scheduled playback to stop
		std::unique_lock<std::mutex> lock(m_mutex);
		m_stoppedCondition.wait(lock, [this]{ return m_running == false; });
	}

	m_deckLinkOutput->DisableAudioOutput();
	m_deckLinkOutput->DisableVideoOutput();

	if (m_audioBuffer != NULL)
		free(m_audioBuffer);
	m_audioBuffer = NULL;
}

void TestPattern::ScheduleNextFrame(bool prerolling)
{
	if (prerolling == false)
	{
		// If not prerolling, make sure that playback is still active
		std::lock_guard<std::mutex> guard(m_mutex);
		if (m_running == false)
			return;
	}
	if (m_outputSignal == kOutputSignalPip)
	{
		if ((m_totalFramesScheduled % m_framesPerSecond) == 0)
		{
			// On each second, schedule a frame of bars
			if (m_deckLinkOutput->ScheduleVideoFrame(m_videoFrameBars.get(), (m_totalFramesScheduled * m_frameDuration), m_frameDuration, m_frameTimescale) != S_OK)
				return;
		}
		else
		{
			// Schedue frames of black
			if (m_deckLinkOutput->ScheduleVideoFrame(m_videoFrameBlack.get(), (m_totalFramesScheduled * m_frameDuration), m_frameDuration, m_frameTimescale) != S_OK)
				return;
		}
	}
	else
	{
		if ((m_totalFramesScheduled % m_framesPerSecond) == 0)
		{
			// On each second, schedule a frame of black
			if (m_deckLinkOutput->ScheduleVideoFrame(m_videoFrameBlack.get(), (m_totalFramesScheduled * m_frameDuration), m_frameDuration, m_frameTimescale) != S_OK)
				return;
		}
		else
		{
			// Schedue frames of color bars
			if (m_deckLinkOutput->ScheduleVideoFrame(m_videoFrameBars.get(), (m_totalFramesScheduled * m_frameDuration), m_frameDuration, m_frameTimescale) != S_OK)
				return;
		}
	}

	m_totalFramesScheduled += 1;
}

void TestPattern::WriteNextAudioSamples()
{
	unsigned int		bufferedSamples;

	// Try to maintain the number of audio samples buffered in the API at a specified waterlevel
	if ((m_deckLinkOutput->GetBufferedAudioSampleFrameCount(&bufferedSamples) == S_OK) && (bufferedSamples < kAudioWaterlevel))
	{
		unsigned int		samplesToEndOfBuffer;
		unsigned int		samplesToWrite;
		unsigned int		samplesWritten;

		samplesToEndOfBuffer = (m_audioBufferSampleLength - m_audioBufferOffset);
		samplesToWrite = (kAudioWaterlevel - bufferedSamples);
		if (samplesToWrite > samplesToEndOfBuffer)
			samplesToWrite = samplesToEndOfBuffer;

		if (m_deckLinkOutput->ScheduleAudioSamples((void*)((unsigned long)m_audioBuffer + (m_audioBufferOffset * m_config->m_audioChannels * m_config->m_audioSampleDepth / 8)), samplesToWrite, 0, 0, &samplesWritten) == S_OK)
		{
			m_audioBufferOffset = ((m_audioBufferOffset + samplesWritten) % m_audioBufferSampleLength);
		}
	}
}

HRESULT TestPattern::CreateFrame(com_ptr<IDeckLinkMutableVideoFrame>& frame, void (*fillFunc)(com_ptr<IDeckLinkVideoFrame>&))
{
	HRESULT								result;
	int32_t								bytesPerRow;
	com_ptr<IDeckLinkMutableVideoFrame>	newMutableVideoFrame = NULL;
	com_ptr<IDeckLinkMutableVideoFrame>	referenceMutableVideoFrame = NULL;
	com_ptr<IDeckLinkVideoConversion>	frameConverter = NULL;

	constexpr BMDPixelFormat	kReferenceFramePixelFormat = bmdFormat8BitYUV;

	result = m_deckLinkOutput->RowBytesForPixelFormat(m_config->m_pixelFormat, m_frameWidth, &bytesPerRow);
	if (result != S_OK)
	{
		fprintf(stderr, "Failed to get row bytes for output video frame\n");
		return result;
	}

	result = m_deckLinkOutput->CreateVideoFrame(m_frameWidth, m_frameHeight, bytesPerRow, m_config->m_pixelFormat, bmdFrameFlagDefault, newMutableVideoFrame.releaseAndGetAddressOf());
	if (result != S_OK)
	{
		fprintf(stderr, "Failed to create video frame\n");
		return result;
	}

	com_ptr<IDeckLinkVideoFrame> newVideoFrame(IID_IDeckLinkVideoFrame, newMutableVideoFrame);
	if (m_config->m_pixelFormat == kReferenceFramePixelFormat)
	{
		fillFunc(newVideoFrame);
	}
	else
	{
		int32_t referenceBytesPerRow;
		
		result = m_deckLinkOutput->RowBytesForPixelFormat(kReferenceFramePixelFormat, m_frameWidth, &referenceBytesPerRow);
		if (result != S_OK)
		{
			fprintf(stderr, "Failed to get row bytes for reference video frame\n");
			return result;
		}

		// Create a black frame in 8 bit YUV and convert to desired format
		result = m_deckLinkOutput->CreateVideoFrame(m_frameWidth, m_frameHeight, referenceBytesPerRow, kReferenceFramePixelFormat, bmdFrameFlagDefault, referenceMutableVideoFrame.releaseAndGetAddressOf());
		if (result != S_OK)
		{
			fprintf(stderr, "Failed to create reference video frame\n");
			return result;
		}

		com_ptr<IDeckLinkVideoFrame> referenceVideoFrame(IID_IDeckLinkVideoFrame, referenceMutableVideoFrame);
		fillFunc(referenceVideoFrame);

		frameConverter = CreateVideoConversionInstance();

		result = frameConverter->ConvertFrame(referenceVideoFrame.get(), newVideoFrame.get());
		if (result != S_OK)
		{
			fprintf(stderr, "Failed to convert frame\n");
			return result;
		}
	}

	frame = newMutableVideoFrame;

	return result;
}

void TestPattern::PrintStatusLine()
{
	printf("\rscheduled %-16lu completed %-16lu displayed late %-16lu dropped %-16lu\r",
		m_totalFramesScheduled, m_totalFramesCompleted, m_totalFramesDisplayedLate, m_totalFramesDropped);
}

/************************* DeckLink API Delegate Methods *****************************/


HRESULT TestPattern::QueryInterface(REFIID iid, LPVOID *ppv)
{
	*ppv = NULL;
	return E_NOINTERFACE;
}

ULONG TestPattern::AddRef()
{
	// gcc atomic operation builtin
	return __sync_add_and_fetch(&m_refCount, 1);
}

ULONG TestPattern::Release()
{
	// gcc atomic operation builtin
	ULONG newRefValue = __sync_sub_and_fetch(&m_refCount, 1);
	if (!newRefValue)
		delete this;
	return newRefValue;
}

HRESULT TestPattern::ScheduledFrameCompleted(IDeckLinkVideoFrame* completedFrame, BMDOutputFrameCompletionResult result)
{
	switch (result)
	{
		case bmdOutputFrameCompleted:
			++m_totalFramesCompleted;
			break;
		case bmdOutputFrameDropped:
			++m_totalFramesDropped;
			break;
		case bmdOutputFrameDisplayedLate:
			++m_totalFramesDisplayedLate;
			break;
		default:
			break;
	}

	PrintStatusLine();

	// When a video frame has been released by the API, schedule another video frame to be output
	ScheduleNextFrame(false);
	return S_OK;
}

HRESULT TestPattern::ScheduledPlaybackHasStopped()
{
	std::lock_guard<std::mutex> guard(m_mutex);
	m_running = false;
	m_stoppedCondition.notify_all();

	return S_OK;
}

HRESULT TestPattern::RenderAudioSamples(bool preroll)
{
	// Provide further audio samples to the DeckLink API until our preferred buffer waterlevel is reached
	WriteNextAudioSamples();

	if (preroll)
	{
		// Start audio and video output
		m_deckLinkOutput->StartScheduledPlayback(0, 100, 1.0);
	}

	return S_OK;
}

/*****************************************/

void FillSine(void* audioBuffer, unsigned long samplesToWrite, unsigned long channels, unsigned long sampleDepth)
{
	if (sampleDepth == 16)
	{
		short*		nextBuffer;

		nextBuffer = (short*)audioBuffer;
		for (unsigned i = 0; i < samplesToWrite; i++)
		{
			short		sample;

			sample = (short)(24576.0 * sin((i * 2.0 * M_PI) / 48.0));
			for (unsigned ch = 0; ch < channels; ch++)
				*(nextBuffer++) = sample;
		}
	}
	else if (sampleDepth == 32)
	{
		int*		nextBuffer;

		nextBuffer = (int*)audioBuffer;
		for (unsigned i = 0; i < samplesToWrite; i++)
		{
			int		sample;

			sample = (int)(1610612736.0 * sin((i * 2.0 * M_PI) / 48.0));
			for (unsigned ch = 0; ch < channels; ch++)
				*(nextBuffer++) = sample;
		}
	}
}

void FillColourBars(com_ptr<IDeckLinkVideoFrame>& theFrame, bool reverse)
{
	unsigned int*	nextWord;
	long			width;
	long			height;
	unsigned int	bars[8] = {0xEA80EA80, 0xD292D210, 0xA910A9A5, 0x90229035, 0x6ADD6ACA, 0x51EF515A, 0x286D28EF, 0x10801080};

	com_ptr<IDeckLinkVideoBuffer> videoBuffer(IID_IDeckLinkVideoBuffer, theFrame);
	if (!videoBuffer)
		return;
	
	if (videoBuffer->StartAccess(bmdBufferAccessWrite) != S_OK)
	{
		return;
	}

	videoBuffer->GetBytes((void**)&nextWord);
	width = theFrame->GetWidth();
	height = theFrame->GetHeight();

	if (reverse)
	{
		for (long y = 0; y < height; y++)
		{
			for (long x = width - 2; x >= 0; x -= 2)
			{
				*(nextWord++) = bars[(x * 8) / width];
			}
		}
	}
	else
	{
		for (long y = 0; y < height; y++)
		{
			for (long x = 0; x < width; x += 2)
			{
				*(nextWord++) = bars[(x * 8) / width];
			}
		}
	}

	videoBuffer->EndAccess(bmdBufferAccessWrite);
}

void FillBlack(com_ptr<IDeckLinkVideoFrame>& theFrame)
{
	unsigned int*	nextWord;
	long			width;
	long			height;
	unsigned long	wordsRemaining;

	com_ptr<IDeckLinkVideoBuffer> videoBuffer(IID_IDeckLinkVideoBuffer, theFrame);
	if (!videoBuffer)
		return;

	if (videoBuffer->StartAccess(bmdBufferAccessWrite) != S_OK)
	{
		return;
	}
	
	videoBuffer->GetBytes((void**)&nextWord);
	width = theFrame->GetWidth();
	height = theFrame->GetHeight();

	wordsRemaining = (width * 2 * height) / 4;

	while (wordsRemaining-- > 0)
		*(nextWord++) = 0x10801080;

	videoBuffer->EndAccess(bmdBufferAccessWrite);
}
