/* -LICENSE-START-
 ** Copyright (c) 2018 Blackmagic Design
 **  
 ** Permission is hereby granted, free of charge, to any person or organization 
 ** obtaining a copy of the software and accompanying documentation (the 
 ** "Software") to use, reproduce, display, distribute, sub-license, execute, 
 ** and transmit the Software, and to prepare derivative works of the Software, 
 ** and to permit third-parties to whom the Software is furnished to do so, in 
 ** accordance with:
 ** 
 ** (1) if the Software is obtained from Blackmagic Design, the End User License 
 ** Agreement for the Software Development Kit ("EULA") available at 
 ** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
 ** 
 ** (2) if the Software is obtained from any third party, such licensing terms 
 ** as notified by that third party,
 ** 
 ** and all subject to the following:
 ** 
 ** (3) the copyright notices in the Software and this entire statement, 
 ** including the above license grant, this restriction and the following 
 ** disclaimer, must be included in all copies of the Software, in whole or in 
 ** part, and all derivative works of the Software, unless such copies or 
 ** derivative works are solely in the form of machine-executable object code 
 ** generated by a source language processor.
 ** 
 ** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 ** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 ** DEALINGS IN THE SOFTWARE.
 ** 
 ** A copy of the Software is available free of charge at 
 ** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
 ** 
 ** -LICENSE-END-
 */

#include <Accelerate/Accelerate.h>
#include <CoreServices/CoreServices.h>
#include <CoreGraphics/CGImage.h>
#include <Foundation/NSURL.h>
#include <Foundation/NSString.h>
#include <Foundation/NSFileManager.h>
#include <ImageIO/CGImageDestination.h>

#include "ImageWriter.h"

HRESULT ImageWriter::GetNextFilenameWithPrefix(const std::string& path, const std::string& filenamePrefix, std::string& nextFileName)
{
	HRESULT result = E_FAIL;
	static int idx = 0;
	
	while (idx < 10000)
	{
		NSString* filename = [NSString stringWithFormat:@"%s/%s%.4d.png", path.c_str(), filenamePrefix.c_str(), idx++];
		
		if (![[NSFileManager defaultManager] fileExistsAtPath:filename])
		{
			nextFileName = std::string([filename UTF8String]);
			result = S_OK;
			break;
		}
	}
	
	return result;
}

HRESULT ImageWriter::WriteBgra32VideoFrameToPNG(IDeckLinkVideoFrame* bgra32VideoFrame, const std::string& pngFilename)
{
	HRESULT result;
	
	NSFileManager* localFileManager = [[NSFileManager alloc] init];
	NSString* pngFilenameString = [[NSString stringWithUTF8String:pngFilename.c_str()] stringByExpandingTildeInPath];
	
	// Ensure video frame has expected pixel format
	if (bgra32VideoFrame->GetPixelFormat() != bmdFormat8BitBGRA)
	{
		fprintf(stderr, "Video frame is not in 8-Bit BGRA pixel format\n");
		return E_FAIL;
	}
	
	// Check whether file already exists
	if ([localFileManager fileExistsAtPath:pngFilenameString])
		return E_FAIL;

	// Query the DeckLink video frame's buffer
	IDeckLinkMacVideoBuffer* videoBuffer = NULL;
	if (bgra32VideoFrame->QueryInterface(IID_IDeckLinkMacVideoBuffer, (void**)&videoBuffer) != S_OK)
	{
		fprintf(stderr, "Could not query DeckLink Video Buffer\n");
		return E_FAIL;
	}
	
	// Create a CVPixelBuffer from the IOSurface-backed video buffer
	CVPixelBufferRef cvPixelBuffer;
	result = videoBuffer->CreateCVPixelBufferRef((void**)&cvPixelBuffer);
	videoBuffer->Release();
	if (result != S_OK)
	{
		fprintf(stderr, "Could not create a CVPixelBuffer object from the video buffer\n");
		return E_FAIL;
	}
	
	// Get the colorspace attachment from the CVPixelBuffer
	CGColorSpaceRef colorspace = nil;
	CFDictionaryRef cvPixelBufferAttachments = CVBufferCopyAttachments(cvPixelBuffer, kCVAttachmentMode_ShouldPropagate);
	if (cvPixelBufferAttachments != nil)
	{
		colorspace = (CGColorSpaceRef)CFDictionaryGetValue(cvPixelBufferAttachments, kCVImageBufferCGColorSpaceKey);
		CFRelease(cvPixelBufferAttachments);
	}
	
	if (! colorspace)
	{
		// Colorspace key not found, use default ITU-R BT.709 colorspace
		colorspace = CGColorSpaceCreateWithName(kCGColorSpaceITUR_709);
	}
	
	// Declare the pixel format for the vImage_Buffer
	vImage_CGImageFormat cgImageFormat = {
		.bitsPerComponent = 8,
		.bitsPerPixel = 32,
		.bitmapInfo = kCGBitmapByteOrder32Little | kCGImageAlphaFirst,
		.colorSpace = colorspace,
	};
	
	CGColorSpaceRelease(colorspace);
	
	vImageCVImageFormatRef cvImageFormat = vImageCVImageFormat_CreateWithCVPixelBuffer(cvPixelBuffer);
	
	CGFloat backgroundColor[] = { 0.0, 0.0, 0.0 };
	vImage_Error imageError;
	vImageConverterRef imageConverterCVtoCG = vImageConverter_CreateForCVToCGImageFormat(cvImageFormat,
																						 &cgImageFormat,
																						 backgroundColor,
																						 vImage_Flags(kvImageNoFlags),
																						 &imageError);
	vImageCVImageFormat_Release(cvImageFormat);

	if (imageError != kvImageNoError)
	{
		CVPixelBufferRelease(cvPixelBuffer);
		fprintf(stderr, "Could not create a vImage converter\n");
		return E_FAIL;
	}
	
	// Lock CVPixelBuffer base address to read into vImageBuffer
	if (CVPixelBufferLockBaseAddress(cvPixelBuffer, kCVPixelBufferLock_ReadOnly) != noErr)
	{
		CVPixelBufferRelease(cvPixelBuffer);
		vImageConverter_Release(imageConverterCVtoCG);
		fprintf(stderr, "Could not lock the CVPixelBuffer base address for reading\n");
		return E_FAIL;
	}

	// Initialize source buffer with no allocation to read from the underlying CVPixelBuffer resource without copying it.
	vImage_Buffer imageBuffer;
	imageError = vImageBuffer_InitForCopyFromCVPixelBuffer(&imageBuffer,
														   imageConverterCVtoCG,
														   cvPixelBuffer,
														   vImage_Flags(kvImageNoAllocate));
	vImageConverter_Release(imageConverterCVtoCG);

	if (imageError != kvImageNoError)
	{
		CVPixelBufferUnlockBaseAddress(cvPixelBuffer, kCVPixelBufferLock_ReadOnly);
		CVPixelBufferRelease(cvPixelBuffer);
		fprintf(stderr, "Could not initialize vImage buffers\n");
		return E_FAIL;
	}
	
	// Create CGImage from vImage buffer with no allocation.
	// The CGImage will read from the locked CVPixelBuffer resource without creating a copy.
	CGImageRef image = vImageCreateCGImageFromBuffer(&imageBuffer,
													 &cgImageFormat,
													 NULL,
													 NULL,
													 vImage_Flags(kvImageNoAllocate),
													 &imageError);
	
	if (imageError != kvImageNoError)
	{
		CVPixelBufferUnlockBaseAddress(cvPixelBuffer, kCVPixelBufferLock_ReadOnly);
		CVPixelBufferRelease(cvPixelBuffer);
		fprintf(stderr, "Could not create a CVPixelBuffer object from the video buffer\n");
		return E_FAIL;
	}

	// Write CGImage to PNG file
	CGImageDestinationRef imageDestination = CGImageDestinationCreateWithURL((CFURLRef)[NSURL fileURLWithPath:pngFilenameString], kUTTypePNG, 1, NULL);
	CGImageDestinationAddImage(imageDestination, image, nil);
	CGImageDestinationFinalize(imageDestination);

	CFRelease(imageDestination);
	
	CVPixelBufferUnlockBaseAddress(cvPixelBuffer, kCVPixelBufferLock_ReadOnly);
	CVPixelBufferRelease(cvPixelBuffer);
	
	return S_OK;
}
