/* -LICENSE-START-
 ** Copyright (c) 2025 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation (the
 ** "Software") to use, reproduce, display, distribute, sub-license, execute,
 ** and transmit the Software, and to prepare derivative works of the Software,
 ** and to permit third-parties to whom the Software is furnished to do so, in
 ** accordance with:
 **
 ** (1) if the Software is obtained from Blackmagic Design, the End User License
 ** Agreement for the Software Development Kit ("EULA") available at
 ** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
 **
 ** (2) if the Software is obtained from any third party, such licensing terms
 ** as notified by that third party,
 **
 ** and all subject to the following:
 **
 ** (3) the copyright notices in the Software and this entire statement,
 ** including the above license grant, this restriction and the following
 ** disclaimer, must be included in all copies of the Software, in whole or in
 ** part, and all derivative works of the Software, unless such copies or
 ** derivative works are solely in the form of machine-executable object code
 ** generated by a source language processor.
 **
 ** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 ** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 **
 ** A copy of the Software is available free of charge at
 ** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
 **
 ** -LICENSE-END-
 */

#include <iostream>
#include <mutex>
#include <stdexcept>

#include "DeckLinkPlayout.h"

class DeckLinkPlayout::CallbackDelegate : public IDeckLinkVideoOutputCallback
{
public:
	explicit CallbackDelegate(DeckLinkPlayout* owner);
	
	// IDeckLinkVideoOutputCallback interface
	HRESULT	ScheduledFrameCompleted(IDeckLinkVideoFrame* completedFrame, BMDOutputFrameCompletionResult result) override;
	HRESULT	ScheduledPlaybackHasStopped() override;
	
	// IUnknown interface
	HRESULT	QueryInterface(REFIID iid, LPVOID *ppv) override;
	ULONG	AddRef() override;
	ULONG	Release() override;

protected:
	~CallbackDelegate() = default;

private:
	DeckLinkPlayout*	m_owner;
	std::atomic<ULONG>	m_refCount;
};


DeckLinkPlayout::CallbackDelegate::CallbackDelegate(DeckLinkPlayout* owner) :
	m_owner(owner),
	m_refCount(1)
{
}

// IDeckLinkVideoOutputCallback interface

HRESULT DeckLinkPlayout::CallbackDelegate::ScheduledFrameCompleted(IDeckLinkVideoFrame* completedFrame, BMDOutputFrameCompletionResult result)
{
	m_owner->scheduledFrameCompleted(com_ptr<IDeckLinkVideoFrame>(completedFrame), result);
	return S_OK;
}

HRESULT DeckLinkPlayout::CallbackDelegate::ScheduledPlaybackHasStopped()
{
	m_owner->scheduledPlaybackStopped();
	return S_OK;
}

// IUnknown interface

HRESULT DeckLinkPlayout::CallbackDelegate::QueryInterface(REFIID iid, LPVOID *ppv)
{
	HRESULT result = S_OK;

	if (ppv == nullptr)
		return E_POINTER;
	
	// Obtain the IUnknown interface and compare it the provided REFIID
	CFUUIDBytes iunknown = CFUUIDGetUUIDBytes(IUnknownUUID);
	if (memcmp(&iid, &iunknown, sizeof(REFIID)) == 0)
	{
		*ppv = this;
		AddRef();
	}
	else if (memcmp(&iid, &IID_IDeckLinkVideoOutputCallback, sizeof(REFIID)) == 0)
	{
		*ppv = static_cast<IDeckLinkVideoOutputCallback*>(this);
		AddRef();
	}
	else
	{
		*ppv = nullptr;
		result = E_NOINTERFACE;
	}
	
	return result;
}

ULONG DeckLinkPlayout::CallbackDelegate::AddRef()
{
	return ++m_refCount;
}

ULONG DeckLinkPlayout::CallbackDelegate::Release()
{
	ULONG newRefValue = --m_refCount;
	if (newRefValue == 0)
		delete this;
	
	return newRefValue;
}

// DeckLinkOutputDevice implementation

DeckLinkPlayout::DeckLinkPlayout(com_ptr<IDeckLink>& deckLink, uint32_t videoPrerollSize) :
	m_deckLink(deckLink),
	m_deckLinkOutput(IID_IDeckLinkOutput, deckLink),
	m_state(PlayoutState::Idle),
	m_videoPrerollSize(videoPrerollSize)
{
	if (!m_deckLinkOutput)
		throw new std::runtime_error("DeckLink device does not have an output interface.");
	
	// Create callback delegate
	m_callbackDelegate = make_com_ptr<CallbackDelegate>(this);

	// Provide the callback delegate to the video output interface
	m_deckLinkOutput->SetScheduledFrameCompletionCallback(m_callbackDelegate.get());
}

DeckLinkPlayout::~DeckLinkPlayout()
{
	disable();
	m_deckLinkOutput->SetScheduledFrameCompletionCallback(nullptr);
}

std::string DeckLinkPlayout::getDeviceName()
{
	CFStringRef displayName;
	if (m_deckLink->GetDisplayName(&displayName) != S_OK)
		return "DeckLink";

	std::string returnString(CFStringGetCStringPtr(displayName, kCFStringEncodingUTF8));
	CFRelease(displayName);
	return returnString;
}

void DeckLinkPlayout::onScheduledFrameCompleted(const ScheduledFrameCompletedHandler& handler)
{
	m_scheduleFrameCompletedHandler = handler;
}

void DeckLinkPlayout::scheduledFrameCompleted(com_ptr<IDeckLinkVideoFrame> completedFrame, BMDOutputFrameCompletionResult result)
{
	if (! m_scheduleFrameCompletedHandler)
		return;
	
	if (result != bmdOutputFrameFlushed && m_state == PlayoutState::Running)
		m_scheduleFrameCompletedHandler();
}

void DeckLinkPlayout::scheduledPlaybackStopped()
{
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		m_state = PlayoutState::Stopped;
	}
	m_stopPlaybackCondition.notify_one();
}

bool DeckLinkPlayout::enable(const BMDDisplayMode displayMode)
{
	BMDVideoOutputFlags				outputFlags = bmdVideoOutputFlagDefault;
	com_ptr<IDeckLinkDisplayMode>	deckLinkDisplayMode;

	if (m_state != PlayoutState::Idle)
	{
		std::cerr << "Unexpected output state." << std::endl;
		return false;
	}
	
	if (m_deckLinkOutput->GetDisplayMode(displayMode, deckLinkDisplayMode.releaseAndGetAddressOf()) != S_OK)
	{
		std::cerr << "Unable to get output display mode." << std::endl;
		return false;
	}
	
	if (deckLinkDisplayMode->GetFrameRate(&m_frameDuration, &m_frameTimescale) != S_OK)
	{
		std::cerr << "Unable to get frame rate for the output display mode." << std::endl;
		return false;
	}
	
	m_frameWidth = (int32_t)deckLinkDisplayMode->GetWidth();
	m_frameHeight = (int32_t)deckLinkDisplayMode->GetHeight();
	
	if (m_deckLinkOutput->EnableVideoOutput(displayMode, outputFlags) != S_OK)
	{
		std::cerr << "Unable to enable output, is the device already in use?" << std::endl;
		return false;
	}
	
	m_state = PlayoutState::Prerolling;

	return true;
}

void DeckLinkPlayout::disable()
{
	bool scheduledPlaybackRunning = false;

	// If scheduled playback is running, stop video and audio streams immediately
	if ((m_deckLinkOutput->IsScheduledPlaybackRunning(&scheduledPlaybackRunning) == S_OK) && scheduledPlaybackRunning)
	{
		m_state = PlayoutState::Stopping;
		
		m_deckLinkOutput->StopScheduledPlayback(0, nullptr, 0);
		
		// Wait for the playback completion callback
		std::unique_lock<std::mutex> lock(m_mutex);
		m_stopPlaybackCondition.wait(lock, [this] { return m_state == PlayoutState::Stopped; } );
	}
	
	// Disable video outputs
	m_deckLinkOutput->DisableVideoOutput();

	m_state = PlayoutState::Idle;
}

bool DeckLinkPlayout::scheduleVideoFrame(com_ptr<IDeckLinkVideoFrame>& videoFrame, const BMDTimeValue streamTime)
{
	// Stop scheduling more frames when stopping.
	if (m_state == PlayoutState::Stopping)
		return true;
	
	if (m_deckLinkOutput->ScheduleVideoFrame(videoFrame.get(), streamTime, m_frameDuration, m_frameTimescale) != S_OK)
	{
		std::cerr << "Unable to schedule video frame for playback." << std::endl;
		return false;
	}
	
	if (m_state == PlayoutState::Prerolling)
	{
		uint32_t bufferedVideoFrameCount;
		
		// Check whether sufficient video frames have been prerolled and playback can start
		if (m_deckLinkOutput->GetBufferedVideoFrameCount(&bufferedVideoFrameCount) != S_OK)
		{
			std::cerr << "Unable to get buffered video frame count." << std::endl;
			return false;
		}

		if (bufferedVideoFrameCount < m_videoPrerollSize)
			return true;
		
		if (m_deckLinkOutput->StartScheduledPlayback(0, m_frameTimescale, 1.0) != S_OK)
		{
			std::cerr << "Unable to start scheduled playback." << std::endl;
			return false;
		}
		
		m_state = PlayoutState::Running;
	}
	
	return true;
}

bool DeckLinkPlayout::createVideoFrame(com_ptr<IDeckLinkMutableVideoFrame>& videoFrame, const BMDPixelFormat pixelFormat, const BMDColorspace colorspace, const com_ptr<IDeckLinkVideoBuffer>& buffer)
{
	int32_t rowBytes;
	if (m_deckLinkOutput->RowBytesForPixelFormat(pixelFormat, m_frameWidth, &rowBytes) != S_OK)
	{
		std::cerr << "Unable to get row bytes for pixel format" << std::endl;
		return false;
	}
	
	if (! buffer)
	{
		if (m_deckLinkOutput->CreateVideoFrame(m_frameWidth,
											   m_frameHeight,
											   rowBytes,
											   pixelFormat,
											   bmdVideoOutputFlagDefault,
											   videoFrame.releaseAndGetAddressOf()) != S_OK)
		{
			std::cerr << "Unable to create output video frame" << std::endl;
			return false;
		}
	}
	else
	{
		if (m_deckLinkOutput->CreateVideoFrameWithBuffer(m_frameWidth,
														 m_frameHeight,
														 rowBytes,
														 pixelFormat,
														 bmdVideoOutputFlagDefault,
														 buffer.get(),
														 videoFrame.releaseAndGetAddressOf()) != S_OK)
		{
			std::cerr << "Unable to create output video frame" << std::endl;
			return false;
		}
	}
	
	com_ptr<IDeckLinkVideoFrameMutableMetadataExtensions> videoFrameMetadata(IID_IDeckLinkVideoFrameMutableMetadataExtensions, videoFrame);
	
	if (videoFrameMetadata->SetInt(bmdDeckLinkFrameMetadataColorspace, (int64_t)colorspace) != S_OK)
	{
		std::cerr << "Unable to set frame colorspace" << std::endl;
		return false;
	}
	
	return true;
}
