/* -LICENSE-START-
** Copyright (c) 2024 Blackmagic Design
**  
** Permission is hereby granted, free of charge, to any person or organization 
** obtaining a copy of the software and accompanying documentation (the 
** "Software") to use, reproduce, display, distribute, sub-license, execute, 
** and transmit the Software, and to prepare derivative works of the Software, 
** and to permit third-parties to whom the Software is furnished to do so, in 
** accordance with:
** 
** (1) if the Software is obtained from Blackmagic Design, the End User License 
** Agreement for the Software Development Kit ("EULA") available at 
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
** 
** (2) if the Software is obtained from any third party, such licensing terms 
** as notified by that third party,
** 
** and all subject to the following:
** 
** (3) the copyright notices in the Software and this entire statement, 
** including the above license grant, this restriction and the following 
** disclaimer, must be included in all copies of the Software, in whole or in 
** part, and all derivative works of the Software, unless such copies or 
** derivative works are solely in the form of machine-executable object code 
** generated by a source language processor.
** 
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
** DEALINGS IN THE SOFTWARE.
** 
** A copy of the Software is available free of charge at 
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
** 
** -LICENSE-END-
*/

#include "stdafx.h"
#include <map>
#include "SourceReader.h"
#include "PlaybackVideoBuffer.h"

// Map the DeckLink buffer access flags to MF locked flags
static const std::map<BMDBufferAccessFlags, MF2DBuffer_LockFlags> kBufferAccessFlagMap =
{
	std::make_pair(bmdBufferAccessRead, MF2DBuffer_LockFlags_Read),
	std::make_pair(bmdBufferAccessWrite, MF2DBuffer_LockFlags_Write),
	std::make_pair(bmdBufferAccessReadAndWrite, MF2DBuffer_LockFlags_ReadWrite),
};


PlaybackVideoBuffer::PlaybackVideoBuffer(CComPtr<IMFSample> readSample, int64_t streamTimestamp, bool flipVertical) :
	m_refCount(1),
	m_read2DBuffer(nullptr),
	m_frameFlags(bmdFrameFlagDefault),
	m_streamTimestamp(streamTimestamp),
	m_lockedBuffer(nullptr),
	m_lockedCount(0)
{
	HRESULT hr = readSample->ConvertToContiguousBuffer(&m_readBuffer);
	if (hr == S_OK)
	{
		m_read2DBuffer = m_readBuffer;

		if (flipVertical)
		{
			// Bottom-up orientation. 
			m_frameFlags |= bmdFrameFlagFlipVertical;
		}
	}
}

BMDTimeValue PlaybackVideoBuffer::GetStreamTime(BMDTimeScale timeScale)
{
	return (BMDTimeValue)(((m_streamTimestamp * timeScale) + (kMFTimescale / 2)) / kMFTimescale);
}

HRESULT PlaybackVideoBuffer::GetBytes(void **buffer)
{
	if (buffer == nullptr)
		return E_POINTER;

	if (!m_lockedCount)
		return E_ACCESSDENIED;

	*buffer = m_lockedBuffer;
	return S_OK;
}

HRESULT PlaybackVideoBuffer::StartAccess(BMDBufferAccessFlags bufferAccessFlags)
{
	if (m_read2DBuffer)
	{
		// If available, use 2D buffer
		auto search = kBufferAccessFlagMap.find(bufferAccessFlags);
		if (search != kBufferAccessFlagMap.end())
		{
			LONG pitch;
			BYTE* bufferStart;
			DWORD bufferLength;
			if (m_read2DBuffer->Lock2DSize(search->second, &m_lockedBuffer, &pitch, &bufferStart, &bufferLength) != S_OK)
				return E_FAIL;
		}
		else
			return E_FAIL;
	}
	else
	{
		// Use non-2D version.
		if (m_readBuffer->Lock(&m_lockedBuffer, nullptr, nullptr) != S_OK)
			return E_FAIL;
	}

	m_lockedCount++;
	
	return S_OK;
}

HRESULT PlaybackVideoBuffer::EndAccess(BMDBufferAccessFlags)
{
	HRESULT hr;

	if (!m_lockedCount)
		return E_UNEXPECTED;

	if (m_read2DBuffer)
		hr = m_read2DBuffer->Unlock2D();
	else
		hr = m_readBuffer->Unlock();

	if (hr != S_OK)
		return E_FAIL;

	m_lockedCount--;
	return S_OK;
}

HRESULT PlaybackVideoBuffer::QueryInterface(REFIID riid, void** ppv)
{
	HRESULT result = E_NOINTERFACE;

	if (ppv == NULL)
		return E_POINTER;

	// Initialise the return result
	*ppv = NULL;

	// Obtain the IUnknown interface and compare it the provided REFIID
	if (riid == IID_IUnknown)
	{
		*ppv = this;
		AddRef();
		result = S_OK;
	}
	else if (riid == IID_IDeckLinkVideoBuffer)
	{
		*ppv = static_cast<IDeckLinkVideoBuffer*>(this);
		AddRef();
		result = S_OK;
	}
	return result;
}

ULONG PlaybackVideoBuffer::AddRef(void)
{
	return ++m_refCount;
}

ULONG PlaybackVideoBuffer::Release(void)
{
	ULONG newRefCount = --m_refCount;
	if (newRefCount == 0)
		delete this;

	return newRefCount;
}
