$png = [System.IO.File]::ReadAllBytes('icons/banana.png')
$ico = [System.Collections.Generic.List[byte]]::new()
$ico.AddRange([byte[]]@(0,0, 1,0, 1,0))
$ico.AddRange([byte[]]@(0, 0, 0, 0, 1,0, 32,0))
$size = [BitConverter]::GetBytes($png.Length)
$ico.AddRange($size)
$offset = [BitConverter]::GetBytes(22)
$ico.AddRange($offset)
$ico.AddRange($png)
[System.IO.File]::WriteAllBytes('icons/banana.ico', $ico.ToArray())
